# Custom Shadowrocket rules with the highest priority.
# Keep only [Rule] section entries and comments here.
# Example:
# DOMAIN-SUFFIX,example.com,DIRECT


#动画疯
DOMAIN-SUFFIX,bahamut.akamaized.net,Proxy
DOMAIN-SUFFIX,bahamut.com.tw,Proxy
DOMAIN-SUFFIX,digicert.com,Proxy
DOMAIN-SUFFIX,fbcdn.net,Proxy
DOMAIN-SUFFIX,gamer.com.tw,Proxy
DOMAIN-SUFFIX,gvt1.com,Proxy
DOMAIN-SUFFIX,hinet.net,Proxy
DOMAIN-SUFFIX,viblast.com,Proxy
USER-AGENT,Anime*,Proxy


#ehen
DOMAIN-SUFFIX,exhentai.org,Proxy
DOMAIN-SUFFIX,e-hentai.org,Proxy
DOMAIN-SUFFIX,ehgt.org,Proxy

#bank
DOMAIN-SUFFIX,www.cncbinternational.com,DIRECT
DOMAIN-SUFFIX,cncbinternational.com,DIRECT
DOMAIN-SUFFIX,velobank.com,DIRECT
DOMAIN-SUFFIX,eastwestbank.com,DIRECT
DOMAIN-KEYWORD,eastwestbank,DIRECT
DOMAIN,msmp.abchina.com.cn,REJECT

DOMAIN-SUFFIX,bangumi.tv,Proxy
DOMAIN-SUFFIX,bgm.tv,Proxy
DOMAIN-SUFFIX,chii.in,Proxy